# Generated by Django 2.2.2 on 2019-06-16 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentInfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='course',
            name='credit_hours',
            field=models.IntegerField(max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='duration',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile',
            field=models.IntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
